### Install required packages

In [3]:
!pip install geocoder
import pandas as pd
import geocoder

Collecting geocoder
  Downloading geocoder-1.38.1-py2.py3-none-any.whl (98 kB)
Requirement already satisfied: click in c:\users\logeshkumar.b\anaconda3\lib\site-packages (from geocoder) (7.0)
Requirement already satisfied: requests in c:\users\logeshkumar.b\anaconda3\lib\site-packages (from geocoder) (2.22.0)
Collecting ratelim
  Downloading ratelim-0.1.6-py2.py3-none-any.whl (4.0 kB)
Requirement already satisfied: future in c:\users\logeshkumar.b\anaconda3\lib\site-packages (from geocoder) (0.18.2)
Requirement already satisfied: six in c:\users\logeshkumar.b\anaconda3\lib\site-packages (from geocoder) (1.14.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\logeshkumar.b\anaconda3\lib\site-packages (from requests->geocoder) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\logeshkumar.b\anaconda3\lib\site-packages (from requests->geocoder) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\logeshkumar.b\anaconda3\lib\site-packages (from requests->geocoder) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\logeshkumar.b\anaconda3\lib\site-packages (from requests->geocoder) (1.25.8)
Requirement already satisfied: decorator in c:\users\logeshkumar.b\anaconda3\lib\site-packages (from ratelim->geocoder) (4.4.1)
Installing collected packages: ratelim, geocoder
Successfully installed geocoder-1.38.1 ratelim-0.1.6

### Load the dataframe from file

In [5]:
neigh_df = pd.read_csv('df.csv')
neigh_df.head()

   Unnamed: 0 PostalCode      Borough                            Neighborhood
0           0        M1B  Scarborough                          Malvern, Rouge
1           1        M1C  Scarborough  Rouge Hill, Port Union, Highland Creek
2           2        M1E  Scarborough       Guildwood, Morningside, West Hill
3           3        M1G  Scarborough                                  Woburn
4           4        M1H  Scarborough                               Cedarbrae

In [9]:
neigh_df.drop('Unnamed: 0',axis=1,inplace=True)

In [10]:
neigh_df

    PostalCode      Borough                                       Neighborhood
0          M1B  Scarborough                                     Malvern, Rouge
1          M1C  Scarborough             Rouge Hill, Port Union, Highland Creek
2          M1E  Scarborough                  Guildwood, Morningside, West Hill
3          M1G  Scarborough                                             Woburn
4          M1H  Scarborough                                          Cedarbrae
..         ...          ...                                                ...
98         M9N         York                                             Weston
99         M9P    Etobicoke                                          Westmount
100        M9R    Etobicoke  Kingsview Village, St. Phillips, Martin Grove ...
101        M9V    Etobicoke  South Steeles, Silverstone, Humbergate, Jamest...
102        M9W    Etobicoke                Northwest, West Humber - Clairville

[103 rows x 3 columns]

### Loading latitude and longitude values from csv

In [12]:
latlng_df = pd.read_csv('Geospatial_Coordinates.csv')
latlng_df.rename(columns = {'Postal Code': 'PostalCode'}, inplace = True)
latlng_df.head()

  PostalCode   Latitude  Longitude
0        M1B  43.806686 -79.194353
1        M1C  43.784535 -79.160497
2        M1E  43.763573 -79.188711
3        M1G  43.770992 -79.216917
4        M1H  43.773136 -79.239476

### Merge the current DF with geo-coordinates DF

In [13]:
neigh_merge_df = pd.merge(neigh_df, latlng_df, on='PostalCode', how='left')
neigh_merge_df.head()

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476

#### export to file the dataframe

In [14]:
neigh_merge_df.to_csv('neigh_merge.csv')